In [2]:
import pandas as pd

In [3]:
dataset=pd.read_csv("ckd.csv")
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:

dataset=pd.get_dummies(dataset,drop_first=True)#get dummies is used to catogorical data handeling and changed numeric data by one hot encoding finaly is gives dummies so droup_first=True is delete first dummie colum
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [5]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [6]:
inde=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [7]:
dep=dataset[['classification_yes']]

In [8]:
inde.shape

(399, 27)

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(inde,dep,test_size=1/3,random_state=0)

In [10]:
dataset["classification_yes"].value_counts()

1    249
0    150
Name: classification_yes, dtype: int64

In [11]:
dataset.shape

(399, 28)

In [12]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
param_grid={'criterion':['gini','entropy','log_loss'],'max_features':['auto','sqrt','log2'],'splitter':['best','random']}
grid=GridSearchCV(DecisionTreeClassifier(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(X_train,Y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

C:\Users\PJ MANI\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning:
30 fits failed out of a total of 90.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\PJ MANI\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\PJ MANI\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 937, in fit
    super().fit(
  File "C:\Users\PJ MANI\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 352, in fit
    criterion = CRITERIA_CLF[self.criterion](
KeyError: 'log_loss'

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\PJ MANI\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:969: UserWarning: One or more of the test scores are non-finite: [0.96587028 0.96272501 0.9554487  0.94009682 0.93646818 0.97380528
 0.95540614 0.96992227 0.90629952 0.9661568  0.9431693  0.96268473
        nan        nan        nan        nan        nan        nan]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [13]:
re=grid.cv_results_
grid_predictions=grid.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,grid_predictions)

In [14]:
cm

array([[51,  0],
       [ 3, 79]], dtype=int64)

In [15]:
from sklearn.metrics import classification_report
clf_report=classification_report(Y_test,grid_predictions)

In [16]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.94      1.00      0.97        51
           1       1.00      0.96      0.98        82

    accuracy                           0.98       133
   macro avg       0.97      0.98      0.98       133
weighted avg       0.98      0.98      0.98       133

In [17]:
from sklearn.metrics import roc_auc_score
roc_auc_score(Y_test,grid.predict_proba(X_test)[:,1])

0.9817073170731707

In [18]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.021874,2.119471e-02,0.006250,0.007654,gini,auto,best,"{'criterion': 'gini', 'max_features': 'auto', ...",0.981569,0.942166,0.962573,0.961826,0.981217,0.965870,0.014636,4
1,0.006250,7.655181e-03,0.009375,0.007655,gini,auto,random,"{'criterion': 'gini', 'max_features': 'auto', ...",0.963284,0.887907,0.981217,0.981217,1.000000,0.962725,0.039170,5
2,0.009375,7.654655e-03,0.006250,0.007654,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.890467,0.924528,0.981217,0.981031,1.000000,0.955449,0.041187,7
3,0.009374,7.653682e-03,0.015625,0.000001,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.926978,0.961755,0.962573,0.905155,0.944023,0.940097,0.021830,10
4,0.021874,2.119437e-02,0.006251,0.007656,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.908501,0.923510,0.907035,0.962264,0.981031,0.936468,0.029892,11
5,0.009375,7.654851e-03,0.006250,0.007655,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.981569,0.981233,0.943651,1.000000,0.962573,0.973805,0.019168,1
6,0.009375,7.654578e-03,0.006251,0.007656,entropy,auto,best,"{'criterion': 'entropy', 'max_features': 'auto...",0.926978,0.962264,0.925524,0.962264,1.000000,0.955406,0.027509,8
7,0.006250,7.654305e-03,0.006250,0.007655,entropy,auto,random,"{'criterion': 'entropy', 'max_features': 'auto...",0.981569,0.961755,0.944023,0.962264,1.000000,0.969922,0.019165,2
8,0.012499,6.249643e-03,0.009377,0.012502,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.890467,0.885265,0.869849,0.962264,0.923652,0.906300,0.033030,12
9,0.015624,1.101896e-06,0.000000,0.000000,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.963284,0.961755,0.962264,0.962264,0.981217,0.966157,0.007546,3
10,0.015625,9.881590e-03,0.003125,0.006250,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.962963,0.943041,0.925524,0.922492,0.961826,0.943169,0.017198,9
11,0.015623,1.530343e-06,0.000000,0.000000,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.963284,0.962636,0.944023,0.981217,0.962264,0.962685,0.011766,6
12,0.006251,7.655415e-03,0.000000,0.000000,log_loss,auto,best,"{'criterion': 'log_loss', 'max_features': 'aut...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
13,0.006250,7.654831e-03,0.000000,0.000000,log_loss,auto,random,"{'criterion': 'log_loss', 'max_features': 'aut...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,14
14,0.009376,7.655434e-03,0.000000,0.000000,log_loss,sqrt,best,"{'criterion': 'log_loss', 'max_features': 'sqr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,15
15,0.015624,5.135693e-07,0.000000,0.000000,log_loss,sqrt,random,"{'criterion': 'log_loss', 'max_features': 'sqr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,16
16,0.006249,7.653604e-03,0.000000,0.000000,log_loss,log2,best,"{'criterion': 'log_loss', 'max_features': 'log...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
17,0.012500,6.250168e-03,0.000000,0.000000,log_loss,log2,random,"{'criterion': 'log_loss', 'max_features': 'log...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,18